# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predictCpp <- function(model, x, num_threads) {
    .Call('_simplerandomforest_predictCpp', PACKAGE = 'simplerandomforest', model, x, num_threads)
}

simplerandomforestCpp <- function(x, y, num_trees, mtry, replace, sample_fraction, num_threads) {
    .Call('_simplerandomforest_simplerandomforestCpp', PACKAGE = 'simplerandomforest', x, y, num_trees, mtry, replace, sample_fraction, num_threads)
}

